[package]
name = "mdlint"
version = "0.1.0"
edition = "2021"
authors = ["kovarimarkofficial@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwalk = "0.8.1"
markdown = { version = "1.0.0-alpha.7" }
